### ISSUE TITLE
[FEATURE]: Astro support

### ISSUE THREAD

**Issue by HyperionU** [HyperionU/Nota-Set#119]
### The Feature

Fully switch over the Nota-Set website from static HTML / CSS / JS to Astro

### Context

With the decision made regarding Hyperion2.0, and successful case study with [U of H Main website](dub.sh/uofh), Hyperion has decided to fully shift over to Astro by the end of 2025.
Similarly, all new sections are to be written in Astro, making it partially mandatory to switch.
The final nail is the decision to move the entirety of Hyperion University's web presence from GitHub Pages to Vercel, which Astro has native support via integrations.

### Requirements

# Phase I: Start with Astro (PR #118)
- [ ] Migrate project to Astro Base
- [ ] Add Tailwind support
- [ ] Add shadcn/ui
- [ ] Components (Mode Toggle, Navbar, etc.)
- [ ] Link to Notes
- [ ] Make it Deploy (Vercel)
- [ ] Prep for Phase II
# Phase II: Migrate to Astro
- [ ] Add Astro-native Sections (#100 - #117)
- [ ] Start shift from HTML to Astro
- [ ] Finish shift from HTML to Astro
- [ ] Prep for Phase III
# Phase III: Beyond Hyperion2.0
- [ ] Auth (Clerk)
- [ ] Error Management (Sentry)
- [ ] Analytics + (Posthog)
- [ ] *add here*

### Code of Conduct

- [X] I agree to follow Nota-Set's Code of Conduct
- [X] I agree to follow Nota-Set's Contribution Guidelines.
- [X] I am aware that Nota-Set's regulator (Hyperion University Office of Software Maintainers, or Ofsom) can sanction me for failure to follow these guidelines.

**Comment by HyperionU** [comment]
Phase 2 officially begins, as of 30 January 2025.
Onward and upward!
-k
:)
